FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 1998

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "1998"]
